[package]
name = "ode45"
version = "0.1.0"
authors = ["blolya <mast-94@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
